name: Explore Disk

on:
  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Disk space #1
      run: |
        df -h
        du -hd 1 / 2> /dev/null
    - uses: actions/checkout@v3
    - name: Disk space #2
      run: |
        df -h
        du -hd 1 / 2>/dev/null
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Explore disk space
      run: |
        df -h
        du -hd 1 / 2> /dev/null
    - name: Explore home
      run: |
        du -hd 1 /home/ 2> /dev/null
    - name: Explore opt
      run: |
        du -hd 1 /opt 2> /dev/null
